export enum MusicalInstrument {
  Piano = 'Piano',
  Bass = 'Bass',
  ElectricGuitar = 'ElectricGuitar',
  AcousticGuitar = 'AcousticGuitar',
  Drums = 'Drums',
  Saxophone = 'Saxophone',
  Trumpet = 'Trumpet',
  Violin = 'Violin',
  Viola = 'Viola',
  Cello = 'Cello',
  MainVoice = 'MainVoice',
  FirstBackingVoice = 'FirstBackingVoice',
  SecondBackingVoice = 'SecondBackingVoice',
  ThirdBackingVoice = 'ThirdBackingVoice',
  SoundTechnician = 'SoundTechnician',
  ProjectionTechnician = 'ProjectionTechnician',
  LogisticsCoordinator = 'LogisticsCoordinator',
  Other = 'Other',
}

export enum VocalRange {
  Soprano = 'Soprano',
  MezzoSoprano = 'MezzoSoprano',
  Alto = 'Alto',
  Tenor = 'Tenor',
  Baritone = 'Baritone',
  Bass = 'Bass',
  Unknown = 'Unknown',
}

export enum MusicalKey {
  C = 'C',
  CSharp = 'C#',
  D = 'D',
  DSharp = 'D#',
  E = 'E',
  F = 'F',
  FSharp = 'F#',
  G = 'G',
  GSharp = 'G#',
  A = 'A',
  ASharp = 'A#',
  B = 'B',
  Cm = 'Cm',
  CSharpM = 'C#m',
  Dm = 'Dm',
  DSharpM = 'D#m',
  Em = 'Em',
  Fm = 'Fm',
  FSharpM = 'F#m',
  Gm = 'Gm',
  GSharpM = 'G#m',
  Am = 'Am',
  ASharpM = 'A#m',
  Bm = 'Bm',
}
