import { zodResolver } from '@hookform/resolvers/zod';
import { router } from 'expo-router';
import { Controller, useForm } from 'react-hook-form';
import { Alert, ScrollView, Text } from 'react-native';
import { WFButton, WFErrorState, WFInput, WFSkeletonUserCard } from '@/shared/components/WFPrimitives';
import { colors } from '@/theme/colors';
import { useUpdateUser } from '../hooks/useUpdateUser';
import { useUserDetail } from '../hooks/useUserDetail';
import { editUserSchema, EditUserFormValues } from '../schemas/userSchemas';
import { MESSAGES } from '@/constants/messages';
export function EditUserScreen({ id }: { id: string }) { const detail = useUserDetail(id); const mutation = useUpdateUser(); const form = useForm<EditUserFormValues>({ resolver: zodResolver(editUserSchema), values: detail.data ? { id, firstName: detail.data.firstName, lastName: detail.data.lastName, phone: detail.data.phone ?? '', mainInstrument: detail.data.mainInstrument ?? undefined, secondaryInstruments: detail.data.secondaryInstruments, vocalRange: detail.data.vocalRange ?? undefined, comfortableKey: detail.data.comfortableKey ?? undefined, status: detail.data.status, roleIds: detail.data.roles.map(r => r.id), email: detail.data.email } : undefined }); if (detail.isLoading) return <ScrollView style={{ flex: 1, backgroundColor: colors.background, padding: 16 }}><WFSkeletonUserCard /></ScrollView>; if (!detail.data) return <WFErrorState message="Usuario no encontrado." />; const submit = form.handleSubmit(async values => { await mutation.mutateAsync(values); Alert.alert(MESSAGES.appName, MESSAGES.userSaved); router.back(); }); return <ScrollView style={{ flex: 1, backgroundColor: colors.background }} contentContainerStyle={{ padding: 16 }}><Text style={{ color: colors.text, fontSize: 28, fontWeight: '900' }}>Editar Usuario</Text><Controller control={form.control} name="firstName" render={({ field, fieldState }) => <WFInput label="Nombre" value={field.value} onChangeText={field.onChange} error={fieldState.error?.message} />} /><Controller control={form.control} name="lastName" render={({ field, fieldState }) => <WFInput label="Apellido" value={field.value} onChangeText={field.onChange} error={fieldState.error?.message} />} /><Controller control={form.control} name="phone" render={({ field, fieldState }) => <WFInput label="Teléfono" value={field.value} onChangeText={field.onChange} error={fieldState.error?.message} />} /><WFInput label="Email" value={detail.data.email} editable={false} /><WFButton loading={mutation.isPending} onPress={submit}>Guardar cambios</WFButton></ScrollView>; }
